title: lucy lai <span class="chinese">赖璐西</span>
logo: '/files/headshot.png'
show_downloads: false
description: cognitive scientist & professor
theme: jekyll-theme-minimal
markdown: kramdown
google_analytics: UA-121197020-1
