title: lucy lai <span class="chinese">賴璐西</span>
logo: '/files/lai_headshot.png'
show_downloads: false
description: neuroscientist & educator
theme: jekyll-theme-minimal
google_analytics: UA-121197020-1
